// Generated by LiveScript 1.5.0
var esvalid;
esvalid = require('esvalid');
module.exports = function(it){
  if (it === null) {
    return null;
  }
  return function(it){
    return function(it){
      switch (false) {
      case !it.length:
        return it;
      default:
        return null;
      }
    }(
    it.filter(function(it){
      var ref$;
      return (ref$ = it.message) !== "given AST node should be of type Program" && ref$ !== "ReturnStatement must be nested within a FunctionExpression or FunctionDeclaration node" && ref$ !== "BreakStatement must have an IterationStatement or SwitchStatement as an ancestor" && ref$ !== "ContinueStatement must have an IterationStatement as an ancestor";
    }));
  }(
  esvalid.errors(
  it));
};